### ISSUE TITLE
Bug: Mines randomly blowing up.

### ISSUE THREAD

**Issue by subz** [SakuraKade/LC-LandminesForAll#7]
I've noticed since using this mod, sometimes mine just blow up randomly. I've seen one person or monster die to a mine then watch other mines around the map also explode for no reason. I've experienced monsters stepping on mines across the map and setting off a mine near a player who is no where near it. This is my only mod that is altering mines.

**Comment by MinaHansen** [comment]
I will add more checks to the mine before exploding stuff like Line of sight etc.
And also I am adding some extra logging.

I will try to reproduce the issue for now.

**Comment by MinaHansen** [comment]
I will close this for now, Please reopen the issue if the issue persists in version 1.0.1
